---
apiVersion: redis.opstreelabs.in/v1alpha1
kind: Redis
metadata:
  name: opstree-redis
spec:
  mode: standalone
  # imageName: opstree/redis:v2.0
  # imagePullPolicy: IfNotPresent
  # redisPassword: "Opstree@1234"
  global:
    image: opstree/redis:v2.0
    imagePullPolicy: IfNotPresent
    redisPassword: "Opstree@1234"
  standaloneServer:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 128Mi
  redisExporter:
    enabled: false
    image: quay.io/opstree/redis-exporter:1.0
    imagePullPolicy: Always
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 128Mi
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: csi-cephfs-sc
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
      selector: {}
  # nodeSelector:
  #   kubernetes.io/hostname: minikube
