---
variables:
  REPO_NAME: gitlab.com/ot-kubernetes/awesome-operators/redis-operator
stages:
  - Deploy

Artifact Publishing:
  stage: Deploy
  image: golang:1.9
  services:
  - docker:dind
  before_script:
    - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
    - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
    - cd $GOPATH/src/$REPO_NAME
  script:
    - tar cvzf redis-operator.tar.gz build
  artifacts:
    paths:
      - *.gz
