---
variables:
  REPO_NAME: gitlab.com/ot-kubernetes/awesome-operators/redis-operator
stages:
  - Build
  - Test
  - Deploy

Building Code:
  stage: Build
  image: opstreedevops/golang:1.11
  services:
  - docker:dind
  before_script:
    - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
    - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
    - cd $GOPATH/src/$REPO_NAME
  script:
    - dep ensure
    - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/redis-operator -ldflags "-X main.commit=${COMMIT} -X main.version=${VERSION}" ./cmd/manager

Building Docker Image:
  stage: Build
  image: docker:stable
  services:
  - docker:dind
  before_script:
    - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
    - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
    - cd $GOPATH/src/$REPO_NAME
  script:
    - mv build/Dockerfile .
    - docker build -t opstreedevops/redis-operator:latest -f Dockerfile .

Creating Artifact:
  stage: Deploy
  image: docker:stable
  services:
  - docker:dind
  before_script:
    - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
    - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
    - cd $GOPATH/src/$REPO_NAME
  script:
    - tar cvzf redis-operator.tar.gz build
  artifacts:
    paths:
      - redis-operator.tar.gz
  only:
    - tags
