title: Redis Operator
lang: en-US
description: A golang based Redis Operator

# use front matter sort
readme_index:
  with_frontmatter: true

sass:
  style: compressed

addons:
  - github
  - gems
  - analytics

edit: true

# theme: null # disable pages default theme
remote_theme: rundocs/jekyll-rtd-theme

exclude:
  - CHANGELOG.md
  - DEVELOPMENT.md
  - GETTING_STARTED.md
  - helm
