title: Redis Operator
lang: en-US
description: A golang based Redis Operator


# theme: null # disable pages default theme
remote_theme: rundocs/jekyll-rtd-theme

exclude:
  - CHANGELOG.md
  - DEVELOPMENT.md
  - GETTING_STARTED.md
  - helm
