---
apiVersion: v1
kind: Service
metadata:
  name: opstree-redis-headless
  labels:
    app: redis
    chart: redis-10.2.1
    release: opstree-redis
    heritage: Helm
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    app: redis
    release: opstree-redis
